<?php

namespace Colzak\EventBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends DocumentRepository
{
    public function eventFilteredSearch($searchParams) {
        $q = $this->createQueryBuilder()->eagerCursor(true);
        $q->field('coordinates')->geoNear((float)$searchParams['lat'], (float)$searchParams['lng'])->spherical(true)->distanceMultiplier(6378.137)->maxDistance((isset($searchParams['radius']) ? $searchParams['radius'] : 20)/6371);

        $q->limit(20);

        return $q->getQuery()->execute()->toArray(false);;
    }
}