<?php

namespace Colzak\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementRepository extends DocumentRepository
{
	public function getByFollowing($following) {
		$q = $this->createQueryBuilder();
		foreach ($following as $profile) {
			$q->field('profile')->references($profile);
		}
		$q->sort('createdAt', 'desc');
		return $q->getQuery()->execute()->toArray(false);
	}
}