<?php

namespace Colzak\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    public function generateUniqueUsername($data) {

        if (!$data['username']) {
            if ( isset($data['first_name']) || isset($data['last_name']) ) {
                $basename = $this->removeAccents(strtolower($data['first_name'] . '.' . $data['last_name']));
            } else {
                $basename = $this->removeAccents(strtolower($data['profile']['firstname'] . '.' . $data['profile']['lastname']));
            }
            
        } else {
            $basename = $data['username'];
        }

        // Get a list of the similar usernames
        $dql = "SELECT u.username FROM ColzakUserBundle:User u";
        $dql .= " WHERE LOWER(u.username) LIKE :username";
        $results = $this->createQueryBuilder('User')
            ->select('username')
            ->field('username')->equals($basename . '%')
            ->getQuery()
            ->execute();

        if (count($results) > 0)
        {
            // Increment an index until a unique username is found
            $idx = 2;
            foreach ($results as $result) {
                $parts = explode('-', $result['username']);
                if (count($parts) > 2 && $parts[2] >= $idx)
                {
                    $idx = $parts[2] + 1;
                }
            }
            $data['username'] = $basename . '.' . $idx;
        }
        else
        {
            $data['username'] = $basename;
        }

        return $data['username'];
    }

    protected function removeAccents($str)
    { 
        $from = array(
            "á", "à", "â", "ã", "ä", "é", "è", "ê", "ë", "í", "ì", "î", "ï", 
            "ó", "ò", "ô", "õ", "ö", "ú", "ù", "û", "ü", "ç", "Á", "À", "Â", 
            "Ã", "Ä", "É", "È", "Ê", "Ë", "Í", "Ì", "Î", "Ï", "Ó", "Ò", "Ô", 
            "Õ", "Ö", "Ú", "Ù", "Û", "Ü", "Ç"
        ); 
        $to = array(
            "a", "a", "a", "a", "a", "e", "e", "e", "e", "i", "i", "i", "i", 
            "o", "o", "o", "o", "o", "u", "u", "u", "u", "c", "A", "A", "A", 
            "A", "A", "E", "E", "E", "E", "I", "I", "I", "I", "O", "O", "O", 
            "O", "O", "U", "U", "U", "U", "C"
        );
        return str_replace($from, $to, $str); 
    }
}