parameters:
#    colzak_file.example.class: Colzak\FileBundle\Example

services:
#    colzak_file.example:
#        class: %colzak_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
