imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ColzakUserBundle, ColzakSearchBundle, ColzakMessageBundle, ColzakEventBundle ]
    filters:
        cssrewrite: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs

doctrine_mongodb:
    connections:
        default:
            server: %database_host%
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    # port:      %mailer_port%
    spool:     
        type: file
        path: "%kernel.cache_dir%/swiftmailer/spool"

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "@ColzakUserBundle/Resources/config/serializer/fos"

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Colzak\UserBundle\Document\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: colzak_user_registration
            validation_groups:  [Registration]
        # confirmation: 
        #     from_email: 
        #         address: no.reply@buskeet.com
        #         sender_name: Buskeet Inscription
        #     enabled: true
        #     template: ColzakUserBundle:Registration:email_confirmed_registration.html.twig
    resetting:
        email:
            from_email:
                address: no.reply@buskeet.com
                sender_name: Buskeet
            template: ColzakUserBundle:ChangePassword:email_resetting_password.html.twig

fos_rest:
    routing_loader:
        default_format: json
    view:
        default_engine: twig
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
    exception:
        codes: ~
        messages: ~
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    format_listener:
        default_priorities: [json, html, '*/*']
        fallback_format: html
        prefer_extension: true
    service:
        router: router
        templating: templating
        serializer: jms_serializer
        view_handler: fos_rest.view_handler.default

sensio_framework_extra:
    view:
        annotations: false

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               "email"
            options:
                display: popup #dialog is optimized for popup window
    # here you will add one (or more) configurations for resource owners