colzak_search:
    resource: "@ColzakSearchBundle/Resources/config/routing.yml"
    prefix:   /

colzak_search_api:
    resource: "@ColzakSearchBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_file:
    resource: "@ColzakFileBundle/Resources/config/routing.yml"
    prefix:   /

colzak_file_api:
    resource: "@ColzakFileBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_portfolio:
    resource: "@ColzakPortfolioBundle/Resources/config/routing.yml"
    prefix:   /portfolio

colzak_portfolio_api:
    resource: "@ColzakPortfolioBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_static:
    resource: "@ColzakStaticBundle/Resources/config/routing.yml"
    prefix:   /

colzak_geo:
    resource: "@ColzakGeoBundle/Resources/config/routing.yml"
    prefix:   /geo

colzak_user:
    resource: "@ColzakUserBundle/Resources/config/routing.yml"
    prefix:   /

colzak_user_api:
    resource: "@ColzakUserBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type:     rest
    options:
        expose: true

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

