NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

colzak_admin:
    resource: "@ColzakAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

colzak_message_api:
    resource: "@ColzakMessageBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_message:
    resource: "@ColzakMessageBundle/Resources/config/routing.yml"
    prefix:   /

colzak_event_api:
    resource: "@ColzakEventBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_event:
    resource: "@ColzakEventBundle/Resources/config/routing.yml"
    prefix:   /

# colzak_media:
#     resource: "@ColzakMediaBundle/Resources/config/routing.yml"
#     prefix:   /

colzak_media_api:
    resource: "@ColzakMediaBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_search:
    resource: "@ColzakSearchBundle/Resources/config/routing.yml"
    prefix:   /

colzak_search_api:
    resource: "Colzak\SearchBundle\Controller\SearchController"
    type: rest

# colzak_portfolio:
#     resource: "@ColzakPortfolioBundle/Resources/config/routing.yml"
#     prefix:   /portfolio

colzak_portfolio_api:
    resource: "@ColzakPortfolioBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_static:
    resource: "@ColzakStaticBundle/Resources/config/routing.yml"
    prefix:   /

colzak_geo_api:
    resource: "@ColzakGeoBundle/Resources/config/routing_api.yml"
    prefix:   /api
    type: rest
    options:
        expose: true

colzak_geo:
    resource: "@ColzakGeoBundle/Resources/config/routing.yml"
    prefix:   /

colzak_user:
    resource: "@ColzakUserBundle/Resources/config/routing.yml"
    prefix:   /

colzak_user_api:
    resource: "Colzak\UserBundle\Controller\UsersController"
    type: rest

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        expose: true

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#HWIOAuthBundle routes
# hwi_oauth_security:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix: /login

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix: /login

# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /login

facebook_login:
    pattern: /login/check-facebook
