security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer: true
                login_path: /login
                check_path: /login_check
                # default_target_path: colzak_user_homepage

            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        # - { path: ^/messages/, role: IS_AUTHENTICATED_FULLY }
        # - { path: ^/profile/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/s/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/account, role: IS_AUTHENTICATED_FULLY }
        # - { path: ^/home, role: IS_AUTHENTICATED_FULLY }
        # - { path: ^/api/users.json, role: ROLE_SUPER_ADMIN }
        # - { path: ^/api/users/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/search/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/geo/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/*, role: ROLE_USER }
