<?php

namespace Colzak\PortfolioBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * InstrumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentRepository extends DocumentRepository
{
	public function findInstrumentsBySlug($slug) {
		return $this->createQueryBuilder('Instrument')
			->field('name')->equals(new \MongoRegex('/.*'.$slug.'.*/i'))
			->getQuery()
			->execute();
	}
}