<?php

namespace Colzak\PortfolioBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends DocumentRepository
{
}