colzak_user_homepage:
    pattern: /profile/{username}
    defaults: { _controller: ColzakUserBundle:Profile:index, username: 'me' }

colzak_user_test_portfolio:
    pattern: /test
    defaults: { _controller: ColzakUserBundle:Profile:test }
# colzak_user_know_me:
#     pattern: /whoami
#     defaults: { _controller: ColzakUserBundle:Profile:knowMe }
