colzak_user_homepage:
    pattern: /profile/{username}
    defaults: { _controller: ColzakUserBundle:Profile:index, username: 'me' }
    options:
        expose: true

colzak_user_homepage:
    pattern: /profile/{username}/{slug1}/{slug2}
    defaults: { _controller: ColzakUserBundle:Profile:index, username: 'me', slug1: '', slug2: '' }
    options:
        expose: true

colzak_user_account:
    pattern: /account
    defaults: { _controller: ColzakUserBundle:Profile:account }

colzak_user_change_email:
    pattern: /account/change-email
    defaults: { _controller: ColzakUserBundle:Profile:changeEmail }
