parameters:
#    colzak_user.example.class: Colzak\UserBundle\Example

services:
#    colzak_user.example:
#        class: %colzak_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
