parameters:
#    colzak_user.example.class: Colzak\UserBundle\Example

services:
#    colzak_user.example:
#        class: %colzak_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    colzak_user.registration.form.type:
        class: Colzak\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, "@service_container"]
        tags:
            - { name: form.type, alias: colzak_user_registration }

    colzak_user.registration.form.eventlistener:
        class: Colzak\UserBundle\Form\EventListener\RegistrationSubscriber
        arguments: ["@doctrine_mongodb.odm.document_manager"]

    colzak.twig.colzak_extension:
        class: Colzak\UserBundle\Twig\ColzakExtension
        tags:
            - { name: twig.extension }

    my_user_provider:
        class: Colzak\UserBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,@doctrine_mongodb.odm.document_manager,{facebook: facebook_id}]

    colzak_user.email_subscriber:
        class: Colzak\UserBundle\EventListener\EmailSubscriber
        arguments: ["@service_container", "@colzak_notification.notification_service"]
        tags:
            - { name: kernel.event_subscriber }

    # colzak_user.user_service:
    #     class: Colzak\UserBundle\Service\UserService
    #     arguments: [ colzak_user.user_manager ]
    #
    # colzak_user.user_manager:
    #     class: Colzak\UserBundle\Manager\UserManager
    #
    # colzak_user.registration.form.eventlistener:
    #     class: Colzak\UserBundle\Form\EventListener\RegistrationSubscriber
    #     arguments: ["@doctrine.orm.entity_manager"]


# FOS\UserBundle\Model\User:
#     exclusion_policy: ALL
#     properties :
#       username :
#         type:     string
#         expose : true
