<?php

namespace Colzak\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends DocumentRepository
{
	public function getByParticipants($sender, $recipient) {
		$q = $this->createQueryBuilder();
		$q->field('participants')->includesReferenceTo($sender);
		$q->field('participants')->includesReferenceTo($recipient);

		return $q->getQuery()->execute()->toArray(false);
	}

	public function getLastThreads($profile, $limit) {
		$q = $this->createQueryBuilder();
		// $q->where('function() { 
		// 	for (var i in this.participants) {
		// 		if (this.participants[i].id == "53be4ae269032d8620000000") return true;
		// 	}
		//  }');
		$q->field('participants')->includesReferenceTo($profile);
		(NULL === $limit ?: $q->limit($limit));

		return $q->getQuery()->execute()->toArray(false);
	}
}