<?php

namespace Colzak\MessageBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends DocumentRepository
{
	public function getByParticipants($sender, $recipient) {
		$q = $this->createQueryBuilder();
		$q->field('participants')->includesReferenceTo($sender);
		$q->field('participants')->includesReferenceTo($recipient);

		return $q->getQuery()->execute()->toArray(false);;
	}
}