parameters:
#    colzak_music.example.class: Colzak\MusicBundle\Example

services:
#    colzak_music.example:
#        class: %colzak_music.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
