colzak_search_result:
    pattern:  /s/{localization}/{direction}
    defaults: { _controller: ColzakSearchBundle:Search:index, localization: 'FR' }
    methods: GET
    options:
        expose: true
