colzak_search_result:
    pattern:  /s/{localization}/{category}
    defaults: { _controller: ColzakSearchBundle:Default:index, localization: 'FR', category: 'all' }
    methods: GET
    options:
        expose: true
