colzak_search_result:
    pattern:  /s/{localization}/{direction}
    defaults: { _controller: ColzakSearchBundle:Search:index, localization: 'FR', direction: '' }
    methods: GET
    options:
        expose: true

colzak_search_result_preview:
    pattern:  /s/{localization}/{direction}/preview/{itemId}
    defaults: { _controller: ColzakSearchBundle:Search:redirect, localization: 'FR' }
    methods: GET
    options:
        expose: true
