parameters:
#    colzak_admin.example.class: Colzak\AdminBundle\Example

services:
#    colzak_admin.example:
#        class: %colzak_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
