parameters:
#    colzak_core.example.class: Colzak\CoreBundle\Example

services:
#    colzak_core.example:
#        class: %colzak_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
