parameters:
#    colzak_core.example.class: Colzak\CoreBundle\Example

services:

    colzak_core.manager:
        abstract: true
        class: Colzak\CoreBundle\Manager\Manager
        calls:
            - [setDocumentManager, ["@doctrine_mongodb.odm.document_manager"]]
