parameters:
#    colzak_portfolio.example.class: Colzak\PortfolioBundle\Example

services:
#    colzak_portfolio.example:
#        class: %colzak_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
