parameters:
#    colzak_media.example.class: Colzak\MediaBundle\Example

services:
#    colzak_media.example:
#        class: %colzak_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
