parameters:
#    colzak_event.example.class: Colzak\EventBundle\Example

services:
#    colzak_event.example:
#        class: %colzak_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
